version: '3.8'

services:
  web:
    image: php:7.4-apache  # Usamos una imagen con Apache y PHP integrados
    container_name: apache
    ports:
      - "80:80" # Mapea el puerto 80 del host al puerto 80 del contenedor
    volumes:
      - ./www:/var/www/html  # Monta ./www en el directorio de Apache
      - ./conf/:/etc/apache2/sites-available/  # Si tienes configuraciones personalizadas de Apache, monta aquí
    depends_on:
      - php
      - db
    networks:
      - backend

  php:
    image: php:7.4-fpm  # Utilizamos PHP-FPM para procesar PHP
    container_name: php
    networks:
      - backend

  db:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306" 
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    depends_on:
      - db
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
