services:
  web:
    image: php:7.4-apache
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./conf/vhosts/:/etc/apache2/sites-available/
    depends_on:
      - php
      - db
    networks:
      - backend
    command: >
      bash -c "a2ensite default.conf prueba.conf ares.conf &&
               apachectl -D FOREGROUND"

  php:
    image: php:7.4-fpm  # Utilizamos PHP-FPM para procesar PHP
    container_name: php
    networks:
      - backend

  db:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --skip-grant-tables
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Permite contraseñas vacías
    ports:
      - "3306:3306"  # Expone MySQL en el puerto 3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:  # Aquí declaramos el volumen
